SET CURRENT SQLID = 'API8';
-- drop table CLIENT;
-- drop table COMPTE;
-- drop table OPERATION;

------------------------------------------------------------
-- 1. TABLE CLIENT
------------------------------------------------------------
CREATE TABLE CLIENT (
    ID_CLIENT INTEGER NOT NULL,
    NOM_CLIENT CHAR(10) NOT NULL,
    PRENOM_CLIENT CHAR(15),
    ADRESSE_CLIENT CHAR(15),
    CONSTRAINT PK_CLIENT PRIMARY KEY (ID_CLIENT)
) IN APIETUDE.API8TS;

COMMIT;

CREATE UNIQUE INDEX ID_CLIENT ON CLIENT (ID_CLIENT ASC)
CLUSTER USING STOGROUP APITEST;

COMMENT ON TABLE CLIENT IS 'TABLE CLIENT';

COMMENT ON CLIENT (
    ID_CLIENT IS 'NUMERO DE COMPTE CLIENT',
    NOM_CLIENT IS 'NOM DU CLIENT',
    PRENOM_CLIENT IS 'PRENOM DU CLIENT',
    ADRESSE_CLIENT IS 'ADRESSE DU CLIENT'
);

COMMIT;
------------------------------------------------------------
-- 2. TABLE COMPTE (version simplifiée)
------------------------------------------------------------
CREATE TABLE COMPTE (
    ID_COMPTE INTEGER NOT NULL,
    ID_CLIENT INTEGER NOT NULL,
    CODE_CB INTEGER   NOT NULL,
    SOLDE DECIMAL(10, 2) DEFAULT 0,
    CONSTRAINT PK_COMPTE PRIMARY KEY (ID_COMPTE),
    CONSTRAINT FKCPTCLI FOREIGN KEY (ID_CLIENT) REFERENCES
    CLIENT (ID_CLIENT) ON DELETE CASCADE
) IN APIETUDE.API8TS;

COMMIT;

CREATE UNIQUE INDEX ID_COMPTE ON COMPTE (ID_COMPTE ASC)
CLUSTER USING STOGROUP APITEST;

COMMENT ON TABLE COMPTE IS 'TABLE COMPTE';

COMMENT ON COMPTE (
    ID_COMPTE IS 'NUMERO DE COMPTE CLIENT',
    CODE_CB IS 'CODE CB',
    ID_CLIENT IS 'NUMERO DE CLIENT',
    SOLDE IS 'SOLDE'
);

COMMIT;
------------------------------------------------------------
-- 3. TABLE OPERATION FICHIER DCLGEN OPE
------------------------------------------------------------
CREATE TABLE OPERATION (
    ID_OPERATION INTEGER NOT NULL,
    ID_COMPTE INTEGER NOT NULL,
    MONTANT_OP DECIMAL(10, 2) NOT NULL,
    TYPE_OP CHAR(1) NOT NULL, 
    DATE_OP DATE NOT NULL,
    CONSTRAINT PK_OP PRIMARY KEY (ID_OPERATION),
        CONSTRAINT FKOPCOMP FOREIGN KEY (ID_COMPTE)
    REFERENCES COMPTE (ID_COMPTE)
    ON DELETE CASCADE
) IN APIETUDE.API8TS;

COMMIT;

CREATE UNIQUE INDEX ID_OPERATION ON OPERATION (ID_OPERATION ASC)
CLUSTER USING STOGROUP APITEST;

COMMENT ON TABLE OPERATION IS 'TABLE OPERATION';

COMMENT ON OPERATION (
    ID_OPERATION IS 'NUMERO DE OPERATION',
    ID_COMPTE IS 'NUMERO DE COMPTE',
    MONTANT_OP IS 'MONTANT DE L''OPERATION',
    TYPE_OP IS 'TYPE D''OPERATION',
    DATE_OP IS 'DATE DE L''OPERATION'
);

COMMIT;

SELECT * FROM CLIENT;

SELECT * FROM COMPTE;

SELECT * FROM OPERATION;